### PR TITLE
Update EmailNormalizer.php

### PR DESCRIPTION
**Pull request by MostafaRabia**
If email wrote like "mostafa.rabia@GMAIL.COM' it won't be normlized, unless it converted to "@gmail.com", so this fix it.
Thanks.

### CODE REVIEW

**Comment by jaulz** [comment]
@Gabrola any chance to merge this?

**Comment by jaulz** [comment]
ah, actually it would make sense to lowercase the whole email so also the username is normalized but I can also do that manually before normalizing it.

**Comment by MostafaRabia** [comment]
@jaulz 
No one would think in this, I would prefer do it in the package it self, so no unexpected problems.

**Comment by Gabrola** [comment]
In practice, emails are typically entirely case insensitive. So you should be using `strcasecmp` for string comparison, or case insensitive columns in RDBMS. Having to convert to lower case might be a sign that you're doing something wrong.

**Comment by Gabrola** [comment]
@MostafaRabia can you make the lowercase implementation optional with the default behavior as-is? That way I can publish that as a minor release without breaking changes.

**Comment by Gabrola** [comment]
@MostafaRabia can you make the lowercase implementation optional with the default behavior as-is? That way I can publish that as a minor release without breaking changes.
Also you'd have to use mb_strtolower for IDN based emails, which is another reason to make sure you use case-insensitivity in the DB directly instead of having to worry about handling internationalized emails correctly.

**Pull request closed without merging**
